language: node_js

node_js: '10.11.0'

script:
  - npm run-script build

deploy:
  fqdn: satom.me
  provider: pages
  local-dir: build
  target-branch: master
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  on:
    branch: source
